// SPLASH SCREEN
export const RESUME_SESSION = 'RESUME_SESSION';
export const ON_PROGRESS_RESUME_SESSION = 'ON_PROGRESS_RESUME_SESSION';
export const ON_FAIL_RESUME_SESSION = 'ON_FAIL_RESUME_SESSION';
export const ON_SUCCESS_RESUME_SESSION = 'ON_SUCCESS_RESUME_SESSION';

// SIGNIN SCREEN
export const SIGN_IN = 'SIGN_IN';
export const ON_PROGRESS_SIGN_IN = 'ON_PROGRESS_SIGN_IN';
export const ON_SUCCESS_SIGN_IN = 'ON_SUCCESS_SIGN_IN';
export const ON_FAILURE_SIGN_IN = 'ON_FAILURE_SIGN_IN';
export const CLEAR_SIGNIN_ERROR = 'CLEAR_SIGNIN_ERROR';

// SIGNOUT SCREEN
export const SIGN_OUT = 'SIGN_OUT';
export const ON_PROGRESS_SIGN_OUT = 'ON_PROGRESS_SIGN_OUT';
export const ON_SUCCESS_SIGN_OUT = 'ON_SUCCESS_SIGN_OUT';
export const ON_FAILURE_SIGN_OUT = 'ON_FAILURE_SIGN_OUT';

// SIGNUP SCREEN
export const SIGN_UP = 'SIGN_UP';
export const ON_PROGRESS_SIGN_UP = 'ON_PROGRESS_SIGN_UP';
export const ON_SUCCESS_SIGN_UP = 'ON_SUCCESS_SIGN_UP';
export const ON_FAILURE_SIGN_UP = 'ON_FAILURE_SIGN_UP';
export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';

//SOCIAL SCREEN
export const SOCIAL_SIGN_IN = 'SOCIAL_SIGN_IN';
export const SOCIAL_ON_PROGRESS_SIGN_IN = 'SOCIAL_ON_PROGRESS_SIGN_IN';
export const SOCIAL_ON_SUCCESS_SIGN_IN = 'SOCIAL_ON_SUCCESS_SIGN_IN';
export const SOCIAL_ON_FAILURE_SIGN_IN = 'SOCIAL_ON_FAILURE_SIGN_IN';
export const SOCIAL_CLEAR_SIGNIN_ERROR = 'SOCIAL_CLEAR_SIGNIN_ERROR';

//FORGOTPASSWORD
export const FORGOTPASS_EMAIL = 'FORGOTPASS_EMAIL';
export const ON_PROGRESS_FORGOTPASS = 'ON_PROGRESS_FORGOTPASS';
export const ON_SUCCESS_FORGOTPASS = 'ON_SUCCESS_FORGOTPASS';
export const ON_FAILURE_FORGOTPASS = 'ON_FAILURE_FORGOTPASS';
export const CLEAR_FORGOTPASS_ERROR = 'CLEAR_FORGOTPASS_ERROR';

// HEALTH SURVEY
export const FETCH_HEALTHSURVEY = 'FETCH_HEALTHSURVEY';
export const FETCH_SYMTOMS_BY_ID = 'FETCH_SYMTOMS_BY_ID';
export const ON_PROGRESS_HEALTHSURVEY = 'ON_PROGRESS_HEALTHSURVEY';
export const CAL_AGE_SCORE = 'CAL_AGE_SCORE';
export const CAL_SYMPTOMS_SCORE = 'CAL_SYMPTOMS_SCORE';
export const CAL_WEIGHT_SCORE = 'CAL_AGE_SCORE';
export const CAL_SMOKER_SCORE = 'CAL_SMOKER_SCORE';
export const CAL_ALCOHOLDRINKER_SCORE = 'CAL_ALCOHOLDRINKER_SCORE';
export const SYMPTOMS_CHECK_UPDATE = 'SYMPTOMS_CHECK_UPDATE';
export const CALL_SUM = 'CALL_SUM';
export const STORE_HS_SCORE = 'STORE_HS_SCORE';
export const GET_HS_SCORE = 'GET_HS_SCORE';

//GUT SURVEY
export const FETCH_GUTSURVEYQUESTION = 'FETCH_GUTSURVEYQUESTION';
export const FETCH_GUTSURVEYEXPIREDDATE = 'FETCH_GUTSURVEYEXPIREDDATE';
export const FLAGVALUEADDGS = 'FLAGVALUEADDGS';

//ADD PROFILE DETAILS

export const FETCH_PHOTO = 'FETCH_PHOTO';
export const FETCH_GENDER_DETAILS = 'FETCH_GENDER_DETAILS';
export const FETCH_WEIGHT_DETAILS = 'FETCH_WEIGHT_DEAILS';
export const FETCH_HEIGHT_DETAILS = 'FETCH_HEIGHT_DETAILS';
export const FETCH_DOB_DETAILS = 'FETCH_DOB_DETAILS';

//EDIT PROFILE DETAILS

export const FETCH_IMAGE_TO_EDIT = 'FETCH_IMAGE_TO_EDIT';
export const FETCH_GENDER_DETAILS_TO_EDIT = 'FETCH_GENDER_DETAILS_TO_EDIT';
export const FETCH_WEIGHT_DETAILS_TO_EDIT = 'FETCH_WEIGHT_DEAILS_TO_EDIT';
export const FETCH_HEIGHT_DETAILS_TO_EDIT = 'FETCH_HEIGHT_DETAILS_TO_EDIT';
export const FETCH_DOB_DETAILS_TO_EDIT = 'FETCH_DOB_DETAILS_TO_EDIT';
export const FETCH_NUMBER_DETAILS_TO_EDIT = 'FETCH_NUMBER_DETAILS_TO_EDIT';
export const FETCH_EMAIL_DETAILS_TO_EDIT = 'FETCH_EMAIL_DETAILS_TO_EDIT';
export const GETGUTGRAPHVALUE = 'GETGUTGRAPHVALUE';

//FOOD PREFERENCES
export const GETALLFOODPREFERENCES = 'GETALLFOODPREFERENCES';
export const ADDUSERPFS = 'ADDUSERPFS';

// NUTRITION MEAL
export const RECIEVE_NUTRITION_MEAL = 'RECIEVE_NUTRITION_MEAL';
export const ADD_NUTRITION_MEAL_BLD = 'ADD_NUTRITION_MEAL_BLD';
export const UPDATE_NUTRITION_MEAL_BLD = 'UPDATE_NUTRITION_MEAL_BLD';
export const EMPTY_NUTRITION_MEAL_BLD = 'EMPTY_NUTRITION_MEAL_BLD';
export const REMOVE_NUTRITION_MEAL = 'REMOVE_NUTRITION_MEAL';
export const RECEIVE_DAILY_NUTRITION_MEAL = 'RECEIVE_DAILY_NUTRITION_MEAL';
export const LOADING_DAILY_NUTRITION_MEAL = 'LOADING_DAILY_NUTRITION_MEAL';
export const GET_DAILY_NUTRITION_MEAL_DATE = 'GET_DAILY_NUTRITION_MEAL_DATE';
export const UPDATE_WHILE_CHECKBOX = 'UPDATE_WHILE_CHECKBOX';
export const FAV_MEAL = 'FAV_MEAL';
export const ADDED_FAV_MEAL = 'ADDED_FAV_MEAL';
export const ADD_NUTRITION_MEAL_FROM_BM = 'ADD_NUTRITION_MEAL_FROM_BM';

//SUGGESTED MEAL
export const GET_SUGGESTED_MEAL = 'GET_SUGGESTED_MEAL';

//FAQ
export const GET_FAQ_LIST = 'GET_FAQ_LIST';
//Filter Tags
export const FILTER_TAGS = 'FILTER_TAGS';
export const SORTBY_FILTERING_DATA = 'SORTBY_FILTERING_DATA';
export const TAGS_FILTERING_DATA = 'TAGS_FILTERING_DATA';

//MEDICATION DONE BY DHANUSH
export const ADD_MEDICATION = 'ADD_MEDICATION';

//UPLOAD REPORT RESULT for biomark report
export const UPLOAD_REPORT_RESULT =  "UPLOAD_REPORT_RESULT";
